#file.dir=C:\spring_study\fileUpload_ex\src\main\resources\static\images
# file이 저장될 위치
file:
  dir: C:/spring_study/fileUpload_ex/src/main/resources/static/images/
# 업로드할 파일의 최대 사이즈와 멀티파트 요청하나에 업로드할 수 있는 파일 사이즈의 최대합
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 4MB
      enabled: true # default



